version: 0.2
# Build 2122
phases:
  pre_build:
    commands:
      - echo pre_build @1.
      - npm install -g typescript
      - npm install -g aws-cdk
      - aws --version
      - cdk --version
      - docker --version
  build:
    commands:
      # Build docker image.
      - cd rythm-price-micro-serv
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 778477161868.dkr.ecr.us-west-2.amazonaws.com
      - docker build -t rythm-price-micro-serv-repo .
      - docker tag rythm-price-micro-serv-repo:latest 778477161868.dkr.ecr.us-west-2.amazonaws.com/rythm-price-micro-serv-repo:latest
      - docker push 778477161868.dkr.ecr.us-west-2.amazonaws.com/rythm-price-micro-serv-repo:latest
      # Run the cdk.
      - cd ..
      - cd rythm-price-micro-serv-cdk
      - npm install
      - npm run build
      - cdk synth "*"
      - cdk deploy "*"
      - cd ..
      # Update the service.
      - cd rythm-price-micro-serv
      - ./update_service.sh
  post_build:
    commands:
      - echo post_build
