version: 0.2
# Build
phases:
  pre_build:
    commands:
      - echo pre_build @1.
      - echo 434
      - npm install -g typescript
      - npm install -g aws-cdk
      - aws --version
      - cdk --version
      - docker --version
  build:
    commands:
      # Create repos in ECR.
      - npm install -g typescript
      - cd rythm-svc-cdk
      - npm install
      - cdk list
      - cdk deploy "RythmSvcCdkStackEcrStack8BB0E4EE"

      # - cd ..
      # Build docker image.
      - cd rythm-svc-price
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 778477161868.dkr.ecr.us-west-2.amazonaws.com
      - docker build -t rythm-svc-price .
      - docker tag rythm-svc-price:latest 778477161868.dkr.ecr.us-west-2.amazonaws.com/rythm-svc-price:latest
      - docker push 778477161868.dkr.ecr.us-west-2.amazonaws.com/rythm-svc-price:latest
      # # Run the cdk.
      # - cd ..
      # - cd rythm-price-micro-serv-cdk
      # - npm install
      # - npm run build
      # - cdk synth "*"
      # - cdk deploy "*" --require-approval=never
      # - cd ..
      # # Update the service.
      # - cd rythm-price-micro-serv
      # # - ./update_service.sh
  post_build:
    commands:
      - echo post_build
